.TH "KChangeLogger/Forms Directory Reference" 3 "Wed Dec 19 2012" "Version 0.6" "KChangeLogger" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KChangeLogger/Forms Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBAbout\fP"
.br
.ti -1c
.RI "directory \fBMaintenance\fP"
.br
.ti -1c
.RI "directory \fBProject\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBMainForm\&.cs\fP"
.br
.ti -1c
.RI "file \fBMainForm\&.Designer\&.cs\fP"
.br
.in -1c
