.TH "KChangeLogger/Forms/Project Directory Reference" 3 "Wed Dec 19 2012" "Version 0.6" "KChangeLogger" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KChangeLogger/Forms/Project Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBMainFormProjects\&.cs\fP"
.br
.ti -1c
.RI "file \fBMainFormProjects\&.Designer\&.cs\fP"
.br
.ti -1c
.RI "file \fBMainFormProjectsInfo\&.cs\fP"
.br
.ti -1c
.RI "file \fBMainFormProjectsInfo\&.Designer\&.cs\fP"
.br
.ti -1c
.RI "file \fBMainFormProjectsNew\&.cs\fP"
.br
.ti -1c
.RI "file \fBMainFormProjectsNew\&.Designer\&.cs\fP"
.br
.in -1c
