.TH "KChangeLogger/Forms/Maintenance Directory Reference" 3 "Wed Dec 19 2012" "Version 0.6" "KChangeLogger" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KChangeLogger/Forms/Maintenance Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBChanges\fP"
.br
.ti -1c
.RI "directory \fBFiles\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBMaintenanceForm\&.cs\fP"
.br
.ti -1c
.RI "file \fBMaintenanceForm\&.Designer\&.cs\fP"
.br
.ti -1c
.RI "file \fBMaintenanceFormEdit\&.cs\fP"
.br
.ti -1c
.RI "file \fBMaintenanceFormEdit\&.Designer\&.cs\fP"
.br
.in -1c
