.TH "KChangeLogger/Forms/About Directory Reference" 3 "Wed Dec 19 2012" "Version 0.6" "KChangeLogger" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KChangeLogger/Forms/About Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBAboutKChange\&.cs\fP"
.br
.ti -1c
.RI "file \fBAboutKChange\&.Designer\&.cs\fP"
.br
.in -1c
