.TH "KChangeLogger" 3 "Wed Dec 19 2012" "Version 0.6" "KChangeLogger" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KChangeLogger \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "package \fBBaseClasses\fP"
.br
.ti -1c
.RI "package \fBProperties\fP"
.br
.ti -1c
.RI "package \fBUtilities\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAboutKChange\fP"
.br
.ti -1c
.RI "class \fBMainForm\fP"
.br
.RI "\fIThe main screen fired upon application start \fP"
.ti -1c
.RI "class \fBMaintenanceFormChanges\fP"
.br
.RI "\fIThe Main Form containing changes information of a given \fBProject\fP Entity \fP"
.ti -1c
.RI "class \fBMaintenanceFormChangesDetail\fP"
.br
.RI "\fIForm containing detailed Changes information of a given change\&. Called from \fBMaintenanceFormChanges\fP \fP"
.ti -1c
.RI "class \fBMaintenanceFormFiles\fP"
.br
.RI "\fIForm showing the files currently linked on the given loaded project\&. Loaded from \fBMaintenanceForm\fP \fP"
.ti -1c
.RI "class \fBMaintenanceFormFilesAdd\fP"
.br
.RI "\fIA simple dialog for adding files\&. Can add files manually (inputting text) or use a OpenFileDialog\&. \fP"
.ti -1c
.RI "class \fBMaintenanceForm\fP"
.br
.RI "\fIScreen allowing you to quickly add a \fBProject\fP change\&. Heart of the application\&. \fP"
.ti -1c
.RI "class \fBMaintenanceFormEdit\fP"
.br
.ti -1c
.RI "class \fBMainFormProjects\fP"
.br
.RI "\fIScreen showing all projects in a DataGridView\&. Called from \fBMainForm\fP \fP"
.ti -1c
.RI "class \fBMainFormProjectsInfo\fP"
.br
.RI "\fIA pop-up containing all information regarding the selected \fBProject\fP\&. \fP"
.ti -1c
.RI "class \fBMainFormProjectsNew\fP"
.br
.RI "\fIA Dialog used for creating a new \fBProject\fP Entity in the database \fP"
.ti -1c
.RI "class \fBKChangeDataContextDataContext\fP"
.br
.RI "\fIData Access Layer for KChange \fP"
.ti -1c
.RI "class \fBProject\fP"
.br
.ti -1c
.RI "class \fBLanguage\fP"
.br
.ti -1c
.RI "class \fBChange_Type\fP"
.br
.ti -1c
.RI "class \fBProject_Change\fP"
.br
.ti -1c
.RI "class \fBProject_File\fP"
.br
.ti -1c
.RI "class \fBLog\fP"
.br
.ti -1c
.RI "class \fBLog_Type\fP"
.br
.ti -1c
.RI "class \fBProgram\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for KChangeLogger from the source code\&.
