.TH "KChangeLogger.Utilities.KLogger" 3 "Wed Dec 19 2012" "Version 0.6" "KChangeLogger" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KChangeLogger.Utilities.KLogger \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBLog\fP (string Message, int LogType)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 8 of file KLogger\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for KChangeLogger from the source code\&.
