.TH "KChangeLogger.Program" 3 "Wed Dec 19 2012" "Version 0.6" "KChangeLogger" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KChangeLogger.Program \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Private Member Functions"

.in +1c
.ti -1c
.RI "static void \fBMain\fP ()"
.br
.RI "\fIThe main entry point for the application\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 8 of file Program\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "static void KChangeLogger\&.Program\&.Main ()\fC [static]\fP, \fC [private]\fP"

.PP
The main entry point for the application\&. 
.PP
Definition at line 14 of file Program\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for KChangeLogger from the source code\&.
