.TH "KChangeLogger.Utilities" 3 "Wed Dec 19 2012" "Version 0.6" "KChangeLogger" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KChangeLogger.Utilities \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBKLogger\fP"
.br
.ti -1c
.RI "class \fBKTextWriter\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for KChangeLogger from the source code\&.
